# run: conda env create --file environments.yml
name: py38pip
channels:
  - conda-forge
dependencies:
  # for pycaret
  - python==3.8
  # for Open3D
  - pip>=20.3
  - pip:
    - --requirement requirements.txt
